### ISSUE TITLE
Overview CoolTShirts

### ISSUE THREAD

**Issue by lucav17** [btan4/sql-scratch-capstone-turn-in#1]
**Basic SQL Queries**
Great use of the different basic SQL queries. These are the ones that we need in order to perform functions on our database. This includes the SELECT, WHERE, FROM SQL commands and involves the use of *.

**Advanced SQL Queries**
Well done using the more complicated syntaxes. This includes the GROUP BY, DISTINCT, COUNT, JOIN, AS, ORDER BY. This shows a good understanding of SQL itself.

**Overall Correctness**
I think you did very good on this! The queries look good to me and the powerpoint has everything that is needed! Well done.

**Overall Grade**
Exceeded Standards. Great job on this!

**Comment by btan4** [comment]
Thank you!
